language: node_js
before_deploy:
  - npm run build
deploy:
  provider: npm
  email: erwingaitano@gmail.com
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
    branch: master
after_success:
- npm run test-coverage-coveralls
